### ISSUE TITLE
GitRepo.changed() fails for empty commits

### ISSUE THREAD

**Issue by OEP** [ScottDuckworth/python-anyvcs#60]
To reproduce:

```
git commit --allow-empty -m 'do nothing'
```

```
>>> import anyvcs
>>> repo = anyvcs.open('.')
>>> repo.changed('master')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pkilgo/.local/lib/python2.7/site-packages/anyvcs-1.3.1-py2.7.egg/anyvcs/git.py", line 328, in changed
    status = meta[3].decode()[0]
IndexError: list index out of range
```

(Fails for anyvcs 1.4.0 too.)

I cannot find a similar functionality for Mercurial or Subversion. You can commit only propchanges in Subversion, but changed() reports the files for which those properties changed.

**Comment by OEP** [comment]
Pull request #61 was merged so this should be fixed in next release.
